[workspace]

members = [
    "xaynet",
    "xaynet-server",
    "xaynet-sdk",
    "xaynet-client",
    "xaynet-core",
    "xaynet-macros",
    "xaynet-ffi",
    # Internal
    "examples",
    "benches",
]
