[package]
name = "xaynet-sdk"
version = "0.1.0"
authors = ["Xayn Engineering <engineering@xaynet.dev>"]
edition = "2018"
description = "`xaynet_sdk` provides building blocks to write participants for the XayNet platform"
license-file = "../../LICENSE"
keywords = ["federated-learning", "fl", "ai", "machine-learning"]
repository = "https://github.com/xaynetwork/xaynet/"
homepage = "https://xaynet.dev/"

[dependencies]
tokio = "0.2.22"
derive_more = { version = "0.99.10", default-features = false, features = ["from"] }
serde = { version = "1.0.116", features = ["derive"] }
bytes = "0.5.6"
sodiumoxide = "0.2.6"
bincode = "1.3.1"
thiserror = "1.0.20"
tracing = "0.1.19"
async-trait = "0.1.40"
xaynet-core = { path = "../xaynet-core", version = "0.1.0" }
reqwest = { version = "0.10.8", default-features = false }

[dev-dependencies]
tower-test = "0.3.0"
tokio-test = "0.2.1"
num = { version = "0.3.0", features = ["serde"] }
xaynet-core = { path = "../xaynet-core", version = "0.1.0", features = ["testutils"] }
serde_json = "1.0.58"

[features]
default = []
tls = ["reqwest/rustls-tls"]
